esphomeyaml:
  name: garage_dht
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

mqtt:
  broker: !secret mqtt_broker_ip
  username: !secret mqtt_username
  password: !secret mqtt_password
  topic_prefix: "home/garage"

# Enable logging
logger:

ota:
  safe_mode: True
  port: 8266
  password: !secret ota_password

sensor:
  - platform: dht
    model: DHT22
    pin: D1
    update_interval: 3min
    humidity:
      name: "Garage Humidity"
      state_topic: "home/garage/humidity/state"
      accuracy_decimals: 1
      icon: 'mdi:water-percent'
      filters:
    temperature:
      name: "Garage Temp"
      state_topic: "home/garage/temperature/state"
      accuracy_decimals: 1
      icon: 'mdi:thermometer'
      filters:
        - lambda: return x * (9.0/5.0) + 32.0;
      unit_of_measurement: "°F"
