esphomeyaml:
  name: spareroom_dht
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

mqtt:
  broker: !secret mqtt_broker_ip
  username: !secret mqtt_username
  password: !secret mqtt_password

# Enable logging
logger:

ota:
  safe_mode: True
  port: 8266
  password: !secret ota_password

sensor:
  - platform: dht
    model: DHT22
    pin: D1
    update_interval: 3min
    humidity:
      filters:
      name: "Spare Room Humidity"
    temperature:
      name: "Spare Room Temp"
      filters:
        - lambda: return x * (9.0/5.0) + 32.0;
      unit_of_measurement: "°F"
